config/routes.rb
Rails.application.routes.draw do

  get 'photo/index/:id' => 'photo#index', as: 'user_photos'
  get 'user/index' => 'user#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord

  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :photos
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController
  def index
    @photos = Photo.where(user_id: params[:id])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoSite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photo/index.html.erb
<%= @photos.count %>
<table>
  <thead>
  <tr>
    <td>Image</td>
    <td>Comments</td>
  </tr>
  </thead>
  <tbody>
  <% @photos.each do |photo| %>
    <tr>
      <td><%= image_tag(photo.file_name , size: "160x150") %></td>
      <% if  photo.comments.size == 0 %>
        <td>No comments</td>
      <% end %>
      <% photo.comments.each do |comment| %>
        <td><%= link_to "#{comment.user.first_name} #{comment.user.last_name}", user_photos_path(comment.user_id) %>
          - <%= comment.comment_text %> <br>
          Created At: <%= comment.date_time %>
        </td>
        <!--      <td><%#= link_to "#{comment.user.first_name} #{comment.user.last_name}", user_photos_path(comment.user_id) %></td>-->
      <% end  %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/user/index.html.erb
<h1>Photosite User List</h1>
<h4> There are <%= @users.count %> Users</h4>
<table>
  <thead>
  <tr>
    <th>User</th>
    <th>First</th>
    <th>Last</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%=  user.id %></td>
      <td><%= link_to user.first_name, user_photos_path(user.id) %></td>
      <td><%= link_to user.last_name, user_photos_path(user.id) %></td>
    </tr>
  <% end %>
  </tbody>
</table>